### ISSUE TITLE
Round/oval shapes?

### ISSUE THREAD

**Issue by jevanveen** [ekatrukha/ComDet#1]
Love this plugin. It's easily the best object based co localization I've found. I noticed on GitHub and in your code that it may be possible to do round shapes for particle detection. Will this be forthcoming? Would be great to have a way to do circularity cutoffs so that it's easier to detect common structures, like nuclei. 

Thanks again for the fantastic work

**Comment by ekatrukha** [comment]
Hello Ed,
thanks for your compliments! Glad it helps.
I'm sorry for delayed reply.
The plugin detects round shapes (as reported by area), but in the end returns rectangular ROIs, since integrated intensity minus background needs to be reported. And perimeter of rectangular ROI is used to estimate background.
I can output circular/round ROI, but it is not clear which one of two should be used in case of two spots colocalization? A ROI with bigger area?
I can estimate circularity and report it in Results table.
What do you think would be a good option for you?
Can you be more precise in what you want to see as an outcome?

**Comment by ekatrukha** [comment]
Added Ovals ROI option in v.0.5.0.
